environment: production
version: v2.3.0
image: lab-app:v2.3.0
deployment_strategy: rolling
infrastructure:
  platform: kubernetes
  provider: aws
  region: us-east-1
  manifest: deployment/kubernetes/deployment.yaml
  provisioning: deployment/terraform
secrets:
  API_KEY: ${API_KEY}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  TOKEN: ${TOKEN}
  AWS_SECRET: ${AWS_SECRET}
